import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import openai
import fastapi

MODEL1_PATH = "/home/vishnu/ros_2025/src/gpt_vision/src/models/grid_model_equalized_120epochs.h5"
MODEL2_PATH = "/home/vishnu/ros_2025/src/gpt_vision/src/models/grid_model_unequal_200epoch.keras"
# IMAGES_PATH = "C:\\Users\\geand\\OneDrive\\Documents\\CSUCI\\SURF 2024\\Grid Model\\grid_model_test_photos"
LABELS_PATH = "/home/vishnu/ros_2025/src/gpt_vision/src/test_images/test_labels.csv"

IMG_RES = (230,440)

FEATURES = [
    "s1yc",     # space 1, yellow circle
    "s1rc",     # space 1, red circle
    "s1bc",     # space 1, blue circle
    "s1gc",     # etc.
    "s1yt",
    "s1rt",
    "s1bt",
    "s1gt",
    "s1ys",
    "s1rs",
    "s1bs",
    "s1gs",
    "s1e",      # space 1 empty
    "s2yc",
    "s2rc",
    "s2bc",
    "s2gc",
    "s2yt",
    "s2rt",
    "s2bt",
    "s2gt",
    "s2ys",
    "s2rs",
    "s2bs",
    "s2gs",
    "s2e",
    "s3yc",
    "s3rc",
    "s3bc",
    "s3gc",
    "s3yt",
    "s3rt",
    "s3bt",
    "s3gt",
    "s3ys",
    "s3rs",
    "s3bs",
    "s3gs",
    "s3e",
    "s4yc",
    "s4rc",
    "s4bc",
    "s4gc",
    "s4yt",
    "s4rt",
    "s4bt",
    "s4gt",
    "s4ys",
    "s4rs",
    "s4bs",
    "s4gs",
    "s4e",
    "s5yc",
    "s5rc",
    "s5bc",
    "s5gc",
    "s5yt",
    "s5rt",
    "s5bt",
    "s5gt",
    "s5ys",
    "s5rs",
    "s5bs",
    "s5gs",
    "s5e",
    "s6yc",
    "s6rc",
    "s6bc",
    "s6gc",
    "s6yt",
    "s6rt",
    "s6bt",
    "s6gt",
    "s6ys",
    "s6rs",
    "s6bs",
    "s6gs",
    "s6e",
    "s7yc",
    "s7rc",
    "s7bc",
    "s7gc",
    "s7yt",
    "s7rt",
    "s7bt",
    "s7gt",
    "s7ys",
    "s7rs",
    "s7bs",
    "s7gs",
    "s7e",
    "s8yc",
    "s8rc",
    "s8bc",
    "s8gc",
    "s8yt",
    "s8rt",
    "s8bt",
    "s8gt",
    "s8ys",
    "s8rs",
    "s8bs",
    "s8gs",
    "s8e",
    "s9yc",
    "s9rc",
    "s9bc",
    "s9gc",
    "s9yt",
    "s9rt",
    "s9bt",
    "s9gt",
    "s9ys",
    "s9rs",
    "s9bs",
    "s9gs",
    "s9e",
    "s10yc",
    "s10rc",
    "s10bc",
    "s10gc",
    "s10yt",
    "s10rt",
    "s10bt",
    "s10gt",
    "s10ys",
    "s10rs",
    "s10bs",
    "s10gs",
    "s10e",
    "s11yc",
    "s11rc",
    "s11bc",
    "s11gc",
    "s11yt",
    "s11rt",
    "s11bt",
    "s11gt",
    "s11ys",
    "s11rs",
    "s11bs",
    "s11gs",
    "s11e",
    "s12yc",
    "s12rc",
    "s12bc",
    "s12gc",
    "s12yt",
    "s12rt",
    "s12bt",
    "s12gt",
    "s12ys",
    "s12rs",
    "s12bs",
    "s12gs",
    "s12e",
    ]

model1 = load_model(MODEL1_PATH)
model2 = load_model(MODEL2_PATH)
print("Models loaded.")